Upgrade example to react native 61.1 (#432)
* Update script

* Update example script

* Upgrade react script in example

* Create a fake accesstoken

* Run upgradeExample script and commit changes

I kept all the icons, fonts
I had to create ./example/android/local.properties file with
sdk.dir = /Users/___USER___/Library/Android/sdk to make it run on android

* Turning off lint

And see if it builds on Travis

* Add jetifier

error: package android.support.annotation does not exist
import android.support.annotation.NonNull;

* Restore android linter and react-native versions

* React-native is not necessary in dev deps

* Restore react native as dev dep

Since it is used in tests