fix: eslintno-unused-expressions
error: Expected an assignment or function call and instead saw an expression: eslintno-unused-expressions, see https://eslint.org/docs/rules/no-unused-expressions