style(eslint): align root and example with the same configuration (#1575)
* fix: remove deprecated extend

see https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

* chore: move lint packages to root

* refactor: move prettierrc to root

* refactor: move tsconfig to root

* chore: align typescript version with root

* refactor: align one eslintrc withboth rules

* style: run lint on root with same rules from example

* fix: ts errors in plugn folder withMapbox

* chore: run lint on all levels

* style: run lint in example with same rules

* fix: eslint errors in example/scenes/Home

* fix: missing Proptypes in SetUserLocationMode

* fix: false errors for used-before-defined in tsx

* style: disable eslint in example test e22 file

* fix: disable prop-type validation for TSX

* fix: missing proptype for AnnotationContent

* fix: eslintno-unused-expressions

error: Expected an assignment or function call and instead saw an expression: eslintno-unused-expressions, see https://eslint.org/docs/rules/no-unused-expressions

* fix: missing proptypes for ShowPointAnnotation

* fix: TS no-var-requires error for JSON require

* refactor: remove unused eslint disable

* refactor: remove unused eslint-disable

* refactor: remove unused eslint-disable

* refactor: remove unused eslint-disable

* fix: re-add eslint-disable - needed for CI ?

* fix: remove unused import fropm test file

* fix: remove unused import in test file

* fix: incorrect propytes for items in Home.js

- super quick fix :(

* refactor: run yarn generate

* chore: project.pbxproj after cocoapods update ?

* build: update Changelog

* Revert "chore: project.pbxproj after cocoapods update ?"

This reverts commit 68cc15e3dad1616dad2e0dde1a3d1af1d2e71200.

* Revert "refactor: run yarn generate"

This reverts commit a257ddbf314c11b9a98e78cbe28fbcd64f943700.

* refactor: remove script `format`